insurance/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('predict.urls', namespace='predict'))
]

predict/urls.py
from django.urls import path
from . import views

app_name = "predict"

urlpatterns = [
    path('', views.predict, name='prediction_page'),
    path('prediction/', views.predict_chances, name='submit_prediction'),
    path('results/', views.view_results, name='results'),
    path('about/', views.about, name='about'),
    path('bmi/', views.bmi, name='bmi'),
    path('calculator/', views.calculator, name='calculator'),
]

predict/models.py
from django.db import models

# Create your models here.

class Prediction_Results(models.Model):

    age = models.FloatField()
    sex = models.FloatField()
    bmi = models.FloatField()
    children = models.FloatField()
    smooker = models.FloatField()
    regression = models.CharField(max_length=30)

    def __str__(self):
        return self.regression

predict/views.py
from django.shortcuts import render
from django.http import JsonResponse
import pandas as pd
from .models import Prediction_Results


def bmi(request):
    return render(request, 'bmi.html')

def calculator(request):
    height = float(request.POST.get('height'))
    weight = float(request.POST.get('weight'))
    bmi = round(weight/((height/100)**2), 2)
    if bmi < 18.5:
        condition = 'Underweight'
        s1 = 'Eat more often'
        s2 = 'Drink Milk'
        s3 = 'Try Weight gainer shakes'
        s4 = 'Use Bigger Plates'
        s5 = 'Add cream to your coffee'
    if (bmi > 18.5) and (bmi < 24.9):
        condition = 'Normal'
        s1 = 'Eat healthy food'
        s2 = 'Do not eat junk food'
        s3 = 'Your meal should contain all the essential nutrients'
        s4 = 'Minimize the intake of alcohol'
        s5 = 'Do regular exercise'
    if bmi > 25:
        condition = 'Overweight'
        s1 = 'Eat Whole grains (whole wheat, steel cut oats, brown rice, quinoa)'
        s2 = 'Eat Vegetables (a colorful variety-not potatoes)'
        s3 = 'Eat Whole fruits (not fruit juices)'
        s4 = 'Eat Nuts, seeds, beans, and other healthful sources of protein (fish and poultry)'
        s5 = 'Eat Plant oils (olive and other vegetable oils)'
    return render(request, 'calculator.html', {'bmi':bmi, 'condition':condition,
           's1':s1, 's2':s2, 's3':s3, 's4':s4, 's5':s5})

def about(request):
    return render(request, 'about.html')

def predict(request):
    return render(request, 'prediction.html')

def predict_chances(request):

    if request.POST.get('action') == 'post':

        
        age = float(request.POST.get('age'))
        sex = float(request.POST.get('sex'))
        bmi = float(request.POST.get('bmi'))
        children = float(request.POST.get('children'))
        smooker = float(request.POST.get('smooker'))

        
        model = pd.read_pickle(r"C:\Users\monster\Desktop\insurance\model.pickle")
       
        result = model.predict([[age, sex, bmi, children, smooker]])

        regression = result[0]

        Prediction_Results.objects.create(age=age, sex=sex, bmi=bmi,children=children, smooker=smooker, regression=regression)

        return JsonResponse({'result': regression, 'age': age,'sex': sex, 'bmi': bmi, 'children': children, 'smooker': smooker},safe=False)

def view_results(request):

    data = {"dataset": Prediction_Results.objects.all()}
    return render(request, "results.html", data)

templates/about.html
{% extends 'homepage.html' %}

{% block main %}

<div class="container pt-3">
    <div class="row justify-content-md-center">
        <div class="col-md-6">
            <h2>About</h2>
            <hr>
            <p>
                This website was made to calculate the cost of health insurance. "Random forest" is used as machine learning algorithm 
                and the accuracy rate of this algorithm is 89.74 percent.
            </p>
            Age: Please enter integer value (from 18 to 65)<br>
            Sex: Please enter 0 or 1 (0=female, 1=male)<br>
            BMI: Please enter value (from 15 to 54)<br>
            Children: Please enter integer value (from 0 to 6)<br>
            Smoker: Please enter 0 or 1 (0=no, 1=yes)<br><br>
            The user must enter values according to the properties in the dataset. Otherwise, there will be a deviation in the accuracy rate.

        </div>
    </div>   
</div>

{% endblock %}

templates/bmi.html
{% extends 'homepage.html' %}

{% block main %}

<title>BMI</title>
<div class="container text-center">
    <h1 class="alert alert-warning">BMI CALCULATOR</h1>
    <br>
    <form action="{% url 'predict:calculator' %}" method='post'>
        {% csrf_token %}
        Weight: <input type="text" name="weight" placeholder="kg" required>
        <br><br>
        Height: <input type="text" name="height" placeholder="cm" required>
        <br><br>
        <input type="submit" value="Calculate" class="btn btn-info">
    </form>
</div>

{% endblock %}

templates/calculator.html
{% extends 'homepage.html' %}
{% block main %}
{% load static %}
<div class="container text-center">
    <h1>Your BMI is: </h1>

    <h2 class="alert alert-success">{{ bmi }} kg/m<sup>2</sup></h2>

    <h2 class="alert alert-primary">You are {{ condition }}
        {% if condition == "Normal" %}<img src="{% static 'Normal.png' %}" width="60" height="60">{% endif %}
        {% if condition == "Underweight" %}<img src="{% static 'underweight.png' %}" width="60" height="60">{% endif %}
        {% if condition == "Overweight" %}<img src="{% static 'overweight.png' %}" width="60" height="60">{% endif %}</h2>
    <div class="alert alert-warning">
        <h3>Some suggestions for you are:</h3>
        <h5>{{ s1 }}</h5>
        <h5>{{ s2 }}</h5>
        <h5>{{ s3 }}</h5>
        <h5>{{ s4 }}</h5>
        <h5>{{ s5 }}</h5>
    </div>
    <br>
    <a href="{% url 'predict:bmi' %}" class="btn btn-danger">Go Back</a>
</div>

{% endblock %}

templates/homepage.html
<!doctype html>
{% load static %}
<html lang="en">
    <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <title>Health Insurance Prediction</title>
    </head>
    <body>


    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="/">Prediction <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/results">Results</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/bmi">Bmi</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/about">About</a>
                </li>
            </ul>
        </div>
    </nav>

    {% block main %}
    {% endblock %}

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </body>
</html>

templates/prediction.html
{% extends "homepage.html" %}

{% block main %}
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Prediction Results</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>Prediction Input:</h5>
                <div>Age: <span id="1"></span></div>
                <div>Sex: <span id="2"></span></div>
                <div>Body Mass Index: <span id="3"></span></div>
                <div>Children: <span id="4"></span></div>
                <div>Smoker: <span id="5"></span></div>
                <h5 class="pt-3">Prediction Regression:</h5>
                <div id="prediction"></div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <a class="btn btn-primary" href="/results" role="button">View Results</a>
            </div>
        </div>
    </div>
</div>

<div class="container pt-5">
    <div class="row justify-content-md-center">
        <div class="col-md-4">
            <h3>Health Insurance Cost Prediction</h3>
            <form action="" id="post-form">
                {% csrf_token %}
                <div class="form-group">
                    <label for="sepal_length">Age</label>
                    <input type="text" step="0.1" class="form-control" id="age" placeholder="Please enter integer value" required>
                </div>
                <div class="form-group">
                    <label for="Sepal Width">Sex</label>
                    <input type="text" step="0.1" class="form-control" id="sex" placeholder="Please enter 0 or 1" required>
                </div>
                <div class="form-group">
                    <label for="petal_length">Body Mass Index</label>
                    <input type="text" step="0.1" class="form-control" id="bmi" placeholder="Please enter value" required>
                </div>
                <div class="form-group">
                    <label for="petal_width">Children</label>
                    <input type="text" step="0.1" class="form-control" id="children" placeholder="Please enter integer value" required>
                </div>
                <div class="form-group">
                    <label for="petal_width">Smoker</label>
                    <input type="text" step="0.1" class="form-control" id="smooker" placeholder="Please enter 0 or 1" required>
                </div>
                <button type="submit" value="Submit" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">Calculate</button>
            </form>
        </div>
    </div>
</div>

<script>
    $(document).on('submit', '#post-form',function(e){
        e.preventDefault();
        $.ajax({
            type:'POST',
            url:'{% url "predict:submit_prediction" %}',
            data:{
                age:$('#age').val(),
                sex:$('#sex').val(),
                bmi:$('#bmi').val(),
                children:$('#children').val(),
                smooker:$('#smooker').val(),
                csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
                action: 'post'
            },
            success:function(json) {
                document.forms["post-form"].reset();
                document.getElementById("prediction").innerHTML = json['result']
                document.getElementById("1").innerHTML = json['age']
                document.getElementById("2").innerHTML = json['sex']
                document.getElementById("3").innerHTML = json['bmi']
                document.getElementById("4").innerHTML = json['children']
                document.getElementById("5").innerHTML = json['smooker']
            },
            error : function(xhr,errmsg,err) {

            }
        });
    })
</script>

{% endblock %}

templates/results.html
{% extends "homepage.html" %}

{% block main %}
    <div class="container pt-5">
        <div class="row">

        <h2>Prediction Results</h2>

            <table class="table">
                <thead>
                <tr>
                <th scope="col">#</th>
                <th scope="col">Age</th>
                <th scope="col">Sex</th>
                <th scope="col">Body Mass Index</th>
                <th scope="col">Children</th>
                <th scope="col">Smoker</th>
                <th scope="col">Prediction Price($)</th>
                </tr>
                </thead>
                <tbody>
                {% for data in dataset %}
                    <tr>
                    <th scope="row">{{ data.id }}</th>
                    <td>{{ data.age }}</td>
                    <td>{{ data.sex }}</td>
                    <td>{{ data.bmi }}</td>
                    <td>{{ data.children }}</td>
                    <td>{{ data.smooker }}</td>
                    <td>{{ data.regression }}</td>
                    </tr>
                {% endfor %}

                </tbody>
            </table>
        </div>
    </div>
{% endblock %}